# These are supported funding model platforms

github:
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: krishnamohanz
thanks_dev:
custom:
  - https://www.krishnamohanproductions.com/donate
  - https://razorpay.me/@krishnamohanyagneswaran
